live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "buttonless"
opacity = 0.75
blur = true

[window.dimensions]
columns = 95
lines = 30

[font]
size = 17.0

[font.bold]
family = "Iosevka Nerd Font"

[font.italic]
family = "Iosevka Nerd Font"

[font.normal]
family = "Iosevka Nerd Font"
#family = "MesloLGS Nerd Font Mono"
style = "Regular"
